# Многоуровневая сборка
FROM golang:1.22.3-alpine AS builder

WORKDIR /app

COPY . .

RUN go mod download
RUN go build -o ./bin/chat_server ./cmd/main.go

FROM alpine:latest

WORKDIR /root/
COPY --from=builder /app/bin/chat_server .
COPY .env .

CMD ["./chat_server", "--config-path=.env"]
